package setuptest

import (
	"io"
	"os"
	"path/filepath"
	"testing"

	"github.com/gruntwork-io/terratest/modules/terraform"
)

const (
	azureRmfileName = "_providers.azurerm.tf"
	azureRmContent  = `
# This file was automatically generated by terratest-terraform-fluent package
# So that automated tests can be run against modules using the AzureRM provider
provider "azurerm" {
features {}
}
`
)

// SetupTestPrepFunc is a function that is used to prepare the test directory before running Terraform.
// It takes a SetupTestResponse struct as a parameter and returns an error.
//
// Example usage is to create a files in the test directory when testing submodules, e.g. AzureRM provider blocks.
type SetupTestPrepFunc func(SetupTestResponse) error

// SetupTestResponse is a struct which contains the temporary directory, the plan, a cleanup function and an error.
type SetupTestResponse struct {
	TmpDir  string
	Plan    *terraform.PlanStruct
	Options *terraform.Options
	Cleanup func()
	Err     error
}

func (resp SetupTestResponse) CreateAzureRMProvidersFile() error {
	fp := filepath.Join(resp.TmpDir, azureRmfileName)
	f, err := os.OpenFile(fp, os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0644)
	if err != nil {
		return err
	}
	defer f.Close()

	_, err = io.WriteString(f, azureRmContent)
	return err
}

// Dirs func begins the fluent test testup process.
// It takes a root directory and a test directory as parameters.
//
// The root directory is the directory containing the terraform code to be tested.
//
// The test directory is the directory containing the test code,
// it should either be blank to test the code in the root,
// or a relative path from the root directory.
func Dirs(rootdir, testdir string) DirType {
	return DirType{
		RootDir: rootdir,
		TestDir: testdir,
	}
}

// DirType is a type which can be used for more fluent setup of a test
type DirType struct {
	RootDir string
	TestDir string
}

// WithVars returns a type which can be used for more fluent setup of a test with variables
func (d DirType) WithVars(vars map[string]interface{}) DirTypeWithVars {
	return DirTypeWithVars{
		RootDir: d.RootDir,
		TestDir: d.TestDir,
		Vars:    vars,
	}
}

// WithVarFiles returns a type which can be used for more fluent setup of a test with variable files
func (d DirType) WithVarFiles(varfiles []string) DirTypeWithVarFiles {
	return DirTypeWithVarFiles{
		RootDir:  d.RootDir,
		TestDir:  d.TestDir,
		VarFiles: varfiles,
	}
}

// DirTypeWithVars is a type which can be used for more fluent setup of a test with variables
type DirTypeWithVars struct {
	RootDir string
	TestDir string
	Vars    map[string]interface{}
}

// DirTypeWithVarFiles is a type which can be used for more fluent setup of a test with variable files
type DirTypeWithVarFiles struct {
	RootDir  string
	TestDir  string
	VarFiles []string
}

// InitPlanShow is a wrapper around terraform.InitAndPlanAndShowWithStructE
// It takes a test object as a parameter and returns a SetupTestResponse.
//
// The SetupTestResponse contains the temporary directory, the plan, a cleanup function and an error.
// The temporary directory is the directory containing a copy of the code specified by the Dirs func.
// The plan is the plan struct generated by terraform, which can be used by the check package.
// The cleanup function is a function which should be used with defer to clean up the temporary directory.
func (dtv DirTypeWithVars) InitPlanShow(t *testing.T) SetupTestResponse {
	resp := CopyTerraformFolderToTempAndCleanUp(t, dtv.RootDir, dtv.TestDir)
	if resp.Err != nil {
		return resp
	}

	opts := getDefaultTerraformOptions(t, resp.TmpDir)
	opts.Vars = dtv.Vars
	plan, err := terraform.InitAndPlanAndShowWithStructE(t, opts)

	resp.Plan = plan
	resp.Err = err
	return resp
}

// InitPlanShow is a wrapper around terraform.InitAndPlanAndShowWithStructE
// It takes a test object and a SetupTestPrepFunc as a parameter and returns a SetupTestResponse.
//
// The SetupTestResponse contains the temporary directory, the plan, a cleanup function and an error.
// The temporary directory is the directory containing a copy of the code specified by the Dirs func.
// The plan is the plan struct generated by terraform, which can be used by the check package.
// The cleanup function is a function which should be used with defer to clean up the temporary directory.
func (dtv DirTypeWithVars) InitPlanShowWithPrepFunc(t *testing.T, f SetupTestPrepFunc) SetupTestResponse {
	resp := CopyTerraformFolderToTempAndCleanUp(t, dtv.RootDir, dtv.TestDir)
	if resp.Err != nil {
		return resp
	}

	if err := f(resp); err != nil {
		resp.Err = err
		return resp
	}

	opts := getDefaultTerraformOptions(t, resp.TmpDir)
	opts.Vars = dtv.Vars
	plan, err := terraform.InitAndPlanAndShowWithStructE(t, opts)

	resp.Options = opts
	resp.Plan = plan
	resp.Err = err
	return resp
}
